
/****** Object:  Database [TestDatabase]    Script Date: 02/23/2009 09:14:51 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'TestDatabase')
DROP DATABASE [TestDatabase]

/****** Object:  Database [TestDatabase]    Script Date: 02/23/2009 09:16:15 ******/
CREATE DATABASE [TestDatabase] ON  PRIMARY 
( NAME = N'DeleteMe', FILENAME = N'[LOCATION]DeleteMe.mdf' , SIZE = 10000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DeleteMe_log', FILENAME = N'[LOCATION]DeleteMe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

EXEC dbo.sp_dbcmptlevel @dbname=N'TestDatabase', @new_cmptlevel=90

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestDatabase].[dbo].[sp_fulltext_database] @action = 'disable'
end

ALTER DATABASE [TestDatabase] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [TestDatabase] SET ANSI_NULLS OFF 

ALTER DATABASE [TestDatabase] SET ANSI_PADDING OFF 

ALTER DATABASE [TestDatabase] SET ANSI_WARNINGS OFF 

ALTER DATABASE [TestDatabase] SET ARITHABORT OFF 

ALTER DATABASE [TestDatabase] SET AUTO_CLOSE OFF 

ALTER DATABASE [TestDatabase] SET AUTO_CREATE_STATISTICS ON 

ALTER DATABASE [TestDatabase] SET AUTO_SHRINK OFF 

ALTER DATABASE [TestDatabase] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [TestDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [TestDatabase] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [TestDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [TestDatabase] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [TestDatabase] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [TestDatabase] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [TestDatabase] SET  ENABLE_BROKER 

ALTER DATABASE [TestDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [TestDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [TestDatabase] SET TRUSTWORTHY OFF 

ALTER DATABASE [TestDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [TestDatabase] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [TestDatabase] SET  READ_WRITE 

ALTER DATABASE [TestDatabase] SET RECOVERY FULL 

ALTER DATABASE [TestDatabase] SET  MULTI_USER 

ALTER DATABASE [TestDatabase] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [TestDatabase] SET DB_CHAINING OFF 